"""Initialize Guardian in a repository."""

import json
from datetime import UTC, datetime
from pathlib import Path

import typer
from rich.console import Console

from guardian.analysis.config_drift import BASELINE_META_FILE
from guardian.analysis.tool_runner import run_command

app = typer.Typer(name="init", help="Initialize Guardian in a repository")
console = Console()

DEFAULT_CONFIG_YAML = """# Guardian Configuration

version: "0.3"

# Analysis settings
analysis:
  # Languages to check
  languages:
    - typescript
    - python

  # Coverage threshold for diff-cover
  coverage_threshold: 80
  coverage_file: coverage.xml

  # Compare branch for diff operations
  compare_branch: origin/main

# Tool paths (auto-detected if not specified)
tools:
  eslint: npx --no-install eslint
  ruff: ruff
  semgrep: semgrep
  diff_cover: diff-cover

# Repository-defined deterministic quality gates
quality:
  commands:
    - name: ruff
      run: uv run ruff check .
      run_on: changed
      include:
        - src/**/*.py
        - tests/**/*.py
        - pyproject.toml
        - uv.lock
    - name: mypy
      run: uv run mypy src/ --ignore-missing-imports
      run_on: full
      include:
        - src/**/*.py
        - pyproject.toml
        - uv.lock
    - name: pytest
      run: uv run pytest
      run_on: full
      include:
        - src/**/*.py
        - tests/**/*.py
        - pyproject.toml
        - uv.lock

# Report settings
reports:
  format: markdown
  keep_count: 10  # Number of reports to retain

# Harness configuration
harness:
  # Which tools are in use
  enabled: []
"""


def _initialize_guardian() -> None:
    """Initialize Guardian configuration in the current repository."""
    repo_root = Path.cwd()

    # Check if we're in a git repository
    result, execution_violation = run_command(
        ["git", "rev-parse", "--git-dir"],
        cwd=repo_root,
        execution_rule="git-rev-parse-execution",
        execution_prefix="Failed to determine git repository",
        execution_suggestion="Ensure git is installed and run inside a repository.",
    )
    if execution_violation is not None:
        console.print(f"[red]Error: {execution_violation.message}[/red]")
        raise typer.Exit(1) from None
    assert result is not None
    if result.returncode != 0:
        console.print("[red]Error: Not in a git repository[/red]")
        raise typer.Exit(1) from None

    guardian_dir = repo_root / ".guardian"
    guardian_dir.mkdir(exist_ok=True)
    reports_dir = guardian_dir / "reports"
    reports_dir.mkdir(exist_ok=True)

    # Create default config if it doesn't exist
    config_file = guardian_dir / "config.yaml"
    if not config_file.exists():
        config_file.write_text(DEFAULT_CONFIG_YAML)
        console.print(f"[green]✓ Created {config_file}[/green]")

    # Create baseline.json if it doesn't exist
    baseline_file = guardian_dir / "baseline.json"
    if not baseline_file.exists():
        baseline_file.write_text("{}\n")
        console.print(f"[green]✓ Created {baseline_file}[/green]")

    # Copy analysis config files from templates
    from guardian.harness.installer import TEMPLATE_DIR

    config_files = {
        "eslint.config.js": guardian_dir / "eslint.config.js",
        "ruff.toml": guardian_dir / "ruff.toml",
        "semgrep-rules.yaml": guardian_dir / "semgrep-rules.yaml",
    }

    for template_name, target_file in config_files.items():
        if not target_file.exists():
            template_file = TEMPLATE_DIR / template_name
            if template_file.exists():
                target_file.write_text(template_file.read_text())
                console.print(f"[green]✓ Created {target_file}[/green]")

    # Initialize baseline hashes from current protected config files.
    from guardian.cli.baseline import generate_baseline_data

    baseline_data, included_files = generate_baseline_data(repo_root)
    baseline_file.write_text(json.dumps(baseline_data, indent=2) + "\n")
    baseline_meta_file = repo_root / BASELINE_META_FILE
    baseline_meta = {
        "acknowledged_policy_change": True,
        "reason": "Initial baseline generated by guardian init",
        "updated_at": datetime.now(UTC).isoformat(),
    }
    baseline_meta_file.write_text(json.dumps(baseline_meta, indent=2) + "\n")
    if included_files:
        console.print(
            f"[green]✓ Recorded baseline hashes for {len(included_files)} config file(s)[/green]"
        )
    else:
        console.print("[yellow]No protected config files found for baseline yet[/yellow]")
    console.print(f"[green]✓ Created {baseline_meta_file}[/green]")

    console.print(f"\n[green]✓ Guardian initialized in {repo_root}[/green]")
    console.print("\n[yellow]Next steps:[/yellow]")
    console.print(
        "  1. Install harness configurations: [cyan]guardian harness install --all[/cyan]"
    )
    console.print("  2. Run verification: [cyan]guardian verify[/cyan]")


@app.callback(invoke_without_command=True)
def init() -> None:
    """Initialize Guardian configuration in the current repository."""
    _initialize_guardian()
